# Generated by Django 6.0.7 on 2026-08-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='Short description directly below title', max_length=255)),
                ('banner_image', models.ImageField(upload_to='events/banners/')),
                ('description', models.TextField(help_text='Main full detail paragraph')),
                ('attendees_count', models.CharField(default='500+ Attendees', max_length=50)),
                ('speakers_count', models.CharField(default='30+ Speakers', max_length=50)),
                ('duration', models.CharField(default='2-Day Event', max_length=50)),
                ('location_name', models.CharField(default='Downtown Convention Center', max_length=100)),
                ('pricing_description', models.TextField(default='Pricing varies based on the services selected and the scale of the event. Contact us for a detailed quote tailored to your specific needs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='website.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='website.event')),
            ],
        ),
    ]
