# Generated by Django 6.0.7 on 2026-08-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_eventenquiry_eventservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantCallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instant Call Request',
                'verbose_name_plural': 'Instant Call Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventenquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Enquiry', 'verbose_name_plural': 'Event Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='eventservice',
            options={'verbose_name': 'Event Service', 'verbose_name_plural': 'Event Services'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('tickets_count', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='website.event')),
            ],
            options={
                'verbose_name': 'Event Booking',
                'verbose_name_plural': 'Event Bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
