# Generated by Django 6.0.7 on 2026-08-06 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_instantcallrequest_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Booking', 'verbose_name_plural': 'Event Bookings'},
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='tickets_count',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_type',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='location',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
