# Generated by Django 6.0.7 on 2026-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_calllog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instantcallrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='instantcallrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instantcallrequest',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instantcallrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
